version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: symfony_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
